version: '3.8'

services:
  family-psychologist-bot:
    build: .
    container_name: family-psychologist-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4-turbo-preview}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./family_psychologist.db}
      - REDIS_URL=redis://redis:6379
      - MCP_SERVER_URL=${MCP_SERVER_URL}
      - MCP_SERVER_TOKEN=${MCP_SERVER_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./memory:/app/memory
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - bot-network

  redis:
    image: redis:7-alpine
    container_name: family-psychologist-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - bot-network

volumes:
  redis-data:

networks:
  bot-network:
    driver: bridge 